//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpapanek.Models
{
    using System;
    using System.Configuration;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            var originalConnectionString = ConfigurationManager.ConnectionStrings["Entities"].ConnectionString;
            var entityBuilder = new EntityConnectionStringBuilder(originalConnectionString);
            var factory = DbProviderFactories.GetFactory(entityBuilder.Provider);
            var providerBuilder = factory.CreateConnectionStringBuilder();
            var dbpass = Environment.GetEnvironmentVariable("APPSETTING_dbpass", EnvironmentVariableTarget.Machine);

            providerBuilder.ConnectionString = entityBuilder.ProviderConnectionString;
            providerBuilder.Add("Password", dbpass);

            Database.Connection.ConnectionString = providerBuilder.ToString();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<education> educations { get; set; }
        public virtual DbSet<job_highlights> job_highlights { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<project_highlights> project_highlights { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<skill_category> skill_category { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    }
}
