//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpapanek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int education_id { get; set; }
        public string institution { get; set; }
        public string credential { get; set; }
        public System.DateTime startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<double> gpa { get; set; }
        public string location { get; set; }
    }
}
