//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dpapanek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public int skills_id { get; set; }
        public int skill_category { get; set; }
        public string skill1 { get; set; }
    
        public virtual skill_category skill_category1 { get; set; }
    }
}
